In [13]:
import numpy as np
from PIL import Image, ImageFilter



In [23]:
# Open image and make into Numpy array
im = Image.open('/img/ppl1.png').convert('RGB')
na = np.array(im)
orig = na.copy()    # Save original
print(na)


[[[220 219 217]
  [225 224 222]
  [225 224 222]
  ...
  [231 230 228]
  [231 230 228]
  [231 230 228]]

 [[225 224 222]
  [229 228 226]
  [230 229 227]
  ...
  [231 230 228]
  [231 230 228]
  [231 230 228]]

 [[226 225 223]
  [230 229 227]
  [231 230 228]
  ...
  [231 230 228]
  [232 231 229]
  [232 231 229]]

 ...

 [[245 245 245]
  [252 252 252]
  [250 250 250]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]

 [[246 246 246]
  [251 251 251]
  [252 252 252]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]

 [[242 242 242]
  [246 246 246]
  [247 247 247]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]]


In [24]:

# Median filter to remove outliers
im = im.filter(ImageFilter.MedianFilter(3))

In [25]:
# Find X,Y coordinates of all yellow pixels
yellowY, yellowX = np.where(np.all(na==[0, 0, 255],axis=2))
#yellowY2, yellowX2= np.where(np.all(na==[0, 0, 255],axis=-2))
zipped = np.column_stack((yellowX,yellowY))
print("xipp",zipped)

xipp []


In [26]:
uniqueY = list(yellowY)
print(uniqueY)
uniqueX= list(set(yellowX))
print(uniqueX)
uniquesetX={uniqueX[0]}
uniquesetY={uniqueY[0]}

[]
[]


IndexError: ignored

In [ ]:


for x in range(0,len(uniqueX)-1):
  if(uniqueX[x+1]-uniqueX[x]>=2):
    uniquesetX.add(uniqueX[x])
    uniquesetX.add(uniqueX[x+1])
uniquesetX.add(uniqueX[len(uniqueX)-1])
uniquesetX=sorted(uniquesetX)
print(uniquesetX)
uniquesetY=list()
for a in uniquesetX:
  for x,y in zipped:
    if(a==x):
      uniquesetY.append(y)
  print("nextx",a)
  print(uniquesetY)

print(uniquesetY)

uniqueset2Y=list()
uniqueset2Y.append(uniquesetY[0])
for x in range(0,len(uniquesetY)-1):
  if(uniquesetY[x+1]-uniquesetY[x]!=1):
    uniqueset2Y.append(uniquesetY[x])
    uniqueset2Y.append(uniquesetY[x+1])
uniqueset2Y.append(uniquesetY[len(uniquesetY)-1])
print("uniqesetY",uniqueset2Y)
uniqueset3Y=list()
for x in range(0,len(uniqueset2Y),4):
  uniqueset3Y.append(uniqueset2Y[x])
  uniqueset3Y.append(uniqueset2Y[x+1])
print("tellmefinal")
print(uniqueset3Y)
#tried rotating
#print("roatted")

#rotimg = im.rotate(90)
#na2=np.array(rotimg)
#yellowrY, yellowrX = np.where(np.all(na2==[0, 0, 255],axis=2))
#uniqueX= list(set(yellowrX))
#print(uniqueX)
# for y in range(0,len(uniqueY)):
#   for x in range(0,len(uniquesetX)):
    #if(na[x][y]==[0,0,255]):
    ##  uniquesetY.add(y)
  



#uniquesetY=set()
#for y in range(0,len(uniqueY)-1):
#  if(uniqueY[y+1]-uniqueY[y]>=2):
  #  print('hyi')
  #  uniquesetY.add(uniqueY[y])
#print(uniquesetY)
#if()
# top, bottom = yellowY[0], yellowY[-1]
# left, right = yellowX[0], yellowX[-1]
# print(top,bottom,left,right)

# # Extract Region of Interest from unblurred original
#ROI = orig[top:bottom, left:right]

# Image.fromarray(ROI).save('result.png')

xipp [[718  22]
 [719  22]
 [720  22]
 ...
 [433  92]
 [434  92]
 [435  92]]
[22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26

In [ ]:
import cv2
img = cv2.imread('/img/ppl1.png')
for i in range(0,len(uniquesetX)-1,2):
  a=uniqueset3Y[i]
  b=uniqueset3Y[i+1]
  c=uniquesetX[i]
  d=uniquesetX[i+1]
  print(i,a,b,c,d)
  face=img[a:b,c:d]

cv2.imwrite("ans1.jpg", face)
  
  
  
# face = img[30:87, 70:129]
cv2.imwrite("ans1.jpg", face)
cv2.waitKey(0)

0 29 88 69 130
2 26 77 245 298
4 35 91 378 436
6 30 85 555 612
8 23 77 717 773
10 31 86 862 919


-1