In [66]:
import numpy as np
import cv2

from PIL import Image, ImageFilter




In [67]:
face_cascade = cv2.CascadeClassifier('/mnt/haarcascade_frontalface_default.xml')
img = cv2.imread('/media/test.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.1, 4)
#img2 = cv2.imread('./test.png')

In [68]:
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
cv2.imwrite('/media/face_detection_result.png', img)

True

In [69]:
from PIL import Image
import os
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
import random
from math import log
from tqdm import tqdm

In [70]:
def getImageMatrix(imageName):
    im = Image.open(imageName, mode="r") 
    pix = im.load()
    color = 1
    if type(pix[0,0]) == int:
        color=0
    image_size = im.size 
    image_matrix = []
    for width in range(int(image_size[0])):
        row = []
        for height in range(int(image_size[1])):
                row.append((pix[width,height]))
        image_matrix.append(row)
    return image_matrix,image_size[0],color

In [71]:
def LogisticEncryption(imageName, key):
    N = 256
    key_list = [ord(x) for x in key]
    G = [key_list[0:4] ,key_list[4:8], key_list[8:12]]
    g = []
    R = 1
    for i in range(1,4):
        s = 0
        for j in range(1,5):
            s += G[i-1][j-1] * (10**(-j))
        g.append(s)
        R = (R*s) % 1
    L = (R + key_list[12]/256) % 1
    S_x = round(((g[0]+g[1]+g[2])*(10**4) + L *(10**4)) % 256)
    V1 = sum(key_list)
    V2 = key_list[0]
    for i in range(1,13):
        V2 = V2 ^ key_list[i]
    V = V2/V1
    L_y = (V+key_list[12]/256) % 1
    S_y = round((V+V2+L_y*10**4) % 256)
    C1_0 = S_x
    C2_0 = S_y
    C = round((L*L_y*10**4) % 256)
    C_r = round((L*L_y*10**4) % 256)
    C_g = round((L*L_y*10**4) % 256)
    C_b = round((L*L_y*10**4) % 256)
    x = 4*(S_x)*(1-S_x)
    y = 4*(S_y)*(1-S_y)
    imageMatrix,dimension, color = getImageMatrix(imageName)
    LogisticEncryptionIm = []
    for i in range(dimension):
        row = []
        for j in range(dimension):
            while x <0.8 and x > 0.2 :
                x = 4*x*(1-x)
            while y <0.8 and y > 0.2 :
                y = 4*y*(1-y)
            x_round = round((x*(10**4))%256)
            y_round = round((y*(10**4))%256)
            C1 = x_round ^ ((key_list[0]+x_round) % N) ^ ((C1_0 + key_list[1])%N)
            C2 = x_round ^ ((key_list[2]+y_round) % N) ^ ((C2_0 + key_list[3])%N) 
            if color:
                C_r =((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((key_list[6]+imageMatrix[i][j][0]) % N) ^ ((C_r + key_list[7]) % N)
                C_g =((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((key_list[6]+imageMatrix[i][j][1]) % N) ^ ((C_g + key_list[7]) % N)
                C_b =((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((key_list[6]+imageMatrix[i][j][2]) % N) ^ ((C_b + key_list[7]) % N)
                row.append((C_r,C_g,C_b))
                C = C_r
            else:
                C = ((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((key_list[6]+imageMatrix[i][j]) % N) ^ ((C + key_list[7]) % N)
                row.append(C)
            x = (x + C/256 + key_list[8]/256 + key_list[9]/256) % 1
            y = (x + C/256 + key_list[8]/256 + key_list[9]/256) % 1
            for ki in range(12):
                key_list[ki] = (key_list[ki] + key_list[12]) % 256
                key_list[12] = key_list[12] ^ key_list[ki]
        LogisticEncryptionIm.append(row)
    im = Image.new('L', (dimension, dimension))
    if color:
        im = Image.new('RGB', (dimension, dimension))
    else: 
        im = Image.new('L', (dimension, dimension)) # L is for Black and white pixels    
    pix = im.load()
    for x in range(dimension):
        for y in range(dimension):
            pix[x, y] = LogisticEncryptionIm[x][y]
    im.save(imageName, "BMP")

In [72]:
image = "/media/induvidual_face"
ext = ".bmp"
key = "abcdefghijklm"

In [73]:
for (x, y, w, h) in faces:
    cropped_image = img[y:y+h, x:x+w]
    cv2.imwrite('/media/induvidual_face.bmp', cropped_image)
    LogisticEncryption(image + ext, key)
    im = Image.open(image + ".bmp", 'r')
    LogisticResult = cv2.imread("/media/induvidual_face.bmp",cv2.IMREAD_COLOR)
    img[y:y+h, x:x+w] = LogisticResult
cv2.imwrite('/media/Encryption_Result.bmp', img)

True

In [74]:
# Open image and make into Numpy array
im = Image.open('/media/Encryption_Result.bmp').convert('RGB')
na = np.array(im)
orig = na.copy()    # Save original
print(na)


[[[220 219 217]
  [225 224 222]
  [226 225 223]
  ...
  [232 231 229]
  [232 231 229]
  [232 231 229]]

 [[227 226 224]
  [232 231 229]
  [232 231 229]
  ...
  [232 231 229]
  [232 231 229]
  [232 231 229]]

 [[225 224 222]
  [230 229 227]
  [231 230 228]
  ...
  [232 231 229]
  [232 231 229]
  [233 232 230]]

 ...

 [[245 245 245]
  [252 252 252]
  [250 250 250]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]

 [[247 247 247]
  [251 251 251]
  [252 252 252]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]

 [[242 242 242]
  [246 246 246]
  [247 247 247]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]]


In [75]:

# Median filter to remove outliers
#im = im.filter(ImageFilter.MedianFilter(3))

In [76]:
# Find X,Y coordinates of all yellow pixels
yellowY, yellowX = np.where(np.all(na==[0, 0, 255],axis=2))
print(yellowX)
#yellowY2, yellowX2= np.where(np.all(na==[0, 0, 255],axis=-2))
zipped = np.column_stack((yellowX,yellowY))
#print("xipp",zipped)

[720 721 722 ... 432 433 434]


In [77]:
uniqueY = list(yellowY)
print(uniqueY)
uniqueX= list(set(yellowX))
print(uniqueX)
uniquesetX={uniqueX[0]}
uniquesetY={uniqueY[0]}

[24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31,

In [78]:


for x in range(0,len(uniqueX)-1):
  if(uniqueX[x+1]-uniqueX[x]>=2):
    uniquesetX.add(uniqueX[x])
    uniquesetX.add(uniqueX[x+1])
uniquesetX.add(uniqueX[len(uniqueX)-1])
uniquesetX=sorted(uniquesetX)
print(uniquesetX)
uniquesetY=list()
for a in uniquesetX:
  for x,y in zipped:
    if(a==x):
      uniquesetY.append(y)
 

#print(uniquesetY)

uniqueset2Y=list()
uniqueset2Y.append(uniquesetY[0])
for x in range(0,len(uniquesetY)-1):
  if(uniquesetY[x+1]-uniquesetY[x]!=1):
    uniqueset2Y.append(uniquesetY[x])
    uniqueset2Y.append(uniquesetY[x+1])
uniqueset2Y.append(uniquesetY[len(uniquesetY)-1])
uniqueset3Y=list()
for x in range(0,len(uniqueset2Y),4):
  uniqueset3Y.append(uniqueset2Y[x])
  uniqueset3Y.append(uniqueset2Y[x+1])
print("tellmefinal")
print(uniqueset3Y)
#tried rotating
#print("roatted")

#rotimg = im.rotate(90)
#na2=np.array(rotimg)
#yellowrY, yellowrX = np.where(np.all(na2==[0, 0, 255],axis=2))
#uniqueX= list(set(yellowrX))
#print(uniqueX)
# for y in range(0,len(uniqueY)):
#   for x in range(0,len(uniquesetX)):
    #if(na[x][y]==[0,0,255]):
    ##  uniquesetY.add(y)
  



#uniquesetY=set()
#for y in range(0,len(uniqueY)-1):
#  if(uniqueY[y+1]-uniqueY[y]>=2):
  #  print('hyi')
  #  uniquesetY.add(uniqueY[y])
#print(uniquesetY)
#if()
# top, bottom = yellowY[0], yellowY[-1]
# left, right = yellowX[0], yellowX[-1]
# print(top,bottom,left,right)

# # Extract Region of Interest from unblurred original
#ROI = orig[top:bottom, left:right]

# Image.fromarray(ROI).save('result.png')

[70, 130, 247, 296, 379, 435, 556, 611, 719, 771, 863, 918]
tellmefinal
[30, 88, 28, 75, 36, 90, 31, 84, 25, 75, 32, 85]


In [79]:
def LogisticDecryption(imageName, key):
    N = 256
    key_list = [ord(x) for x in key]

    G = [key_list[0:4] ,key_list[4:8], key_list[8:12]]
    g = []
    R = 1
    for i in range(1,4):
        s = 0
        for j in range(1,5):
            s += G[i-1][j-1] * (10**(-j))
        g.append(s)
        R = (R*s) % 1
    
    L_x = (R + key_list[12]/256) % 1
    S_x = round(((g[0]+g[1]+g[2])*(10**4) + L_x *(10**4)) % 256)
    V1 = sum(key_list)
    V2 = key_list[0]
    for i in range(1,13):
        V2 = V2 ^ key_list[i]
    V = V2/V1

    L_y = (V+key_list[12]/256) % 1
    S_y = round((V+V2+L_y*10**4) % 256)
    C1_0 = S_x
    C2_0 = S_y
    
    C = round((L_x*L_y*10**4) % 256)
    I_prev = C
    I_prev_r = C
    I_prev_g = C
    I_prev_b = C
    I = C
    I_r = C
    I_g = C
    I_b = C
    x_prev = 4*(S_x)*(1-S_x)
    y_prev = 4*(L_x)*(1-S_y)
    x = x_prev
    y = y_prev
    imageMatrix, dimension, color = getImageMatrix(imageName)

    henonDecryptedImage = []
    for i in range(dimension):
        row = []
        for j in range(dimension):
            while x <0.8 and x > 0.2 :
                x = 4*x*(1-x)
            while y <0.8 and y > 0.2 :
                y = 4*y*(1-y)
            x_round = round((x*(10**4))%256)
            y_round = round((y*(10**4))%256)
            C1 = x_round ^ ((key_list[0]+x_round) % N) ^ ((C1_0 + key_list[1])%N)
            C2 = x_round ^ ((key_list[2]+y_round) % N) ^ ((C2_0 + key_list[3])%N) 
            if color:
                I_r = ((((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((I_prev_r + key_list[7]) % N) ^ imageMatrix[i][j][0]) + N-key_list[6])%N
                I_g = ((((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((I_prev_g + key_list[7]) % N) ^ imageMatrix[i][j][1]) + N-key_list[6])%N
                I_b = ((((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((I_prev_b + key_list[7]) % N) ^ imageMatrix[i][j][2]) + N-key_list[6])%N
                I_prev_r = imageMatrix[i][j][0]
                I_prev_g = imageMatrix[i][j][1]
                I_prev_b = imageMatrix[i][j][2]
                row.append((I_r,I_g,I_b))
                x = (x +  imageMatrix[i][j][0]/256 + key_list[8]/256 + key_list[9]/256) % 1
                y = (x +  imageMatrix[i][j][0]/256 + key_list[8]/256 + key_list[9]/256) % 1  
            else:
                I = ((((key_list[4]+C1) % N) ^ ((key_list[5]+C2) % N) ^ ((I_prev+key_list[7]) % N) ^ imageMatrix[i][j]) + N-key_list[6])%N
                I_prev = imageMatrix[i][j]
                row.append(I)
                x = (x +  imageMatrix[i][j]/256 + key_list[8]/256 + key_list[9]/256) % 1
                y = (x +  imageMatrix[i][j]/256 + key_list[8]/256 + key_list[9]/256) % 1
            for ki in range(12):
                key_list[ki] = (key_list[ki] + key_list[12]) % 256
                key_list[12] = key_list[12] ^ key_list[ki]
        henonDecryptedImage.append(row)
    if color:
        im = Image.new("RGB", (dimension, dimension))
    else: 
        im = Image.new("L", (dimension, dimension)) # L is for Black and white pixels
    pix = im.load()
    for x in range(dimension):
        for y in range(dimension):
            pix[x, y] = henonDecryptedImage[x][y]
    im.save(imageName.split('_')[0], "PNG")
    print("done")

In [80]:
image = "/media/tempdecrypt"
ext = ".bmp"
key = "abcdefghijklm"

In [81]:
import cv2
img = cv2.imread('/media/Encryption_Result.bmp')
for i in range(0,len(uniquesetX)-1,2):
  a=uniqueset3Y[i]
  b=uniqueset3Y[i+1]
  c=uniquesetX[i]
  d=uniquesetX[i+1]
  print(i,a,b,c,d)
  face=img[a:b,c:d]
  cv2.imwrite('/media/tempdecrypt.bmp', face)
  LogisticDecryption(image + ext, key)
  im = Image.open(image + ".bmp", 'r')
  LogisticResult = cv2.imread("/media/tempdecrypt.bmp",cv2.IMREAD_COLOR)
  img[a:b,c:d] = LogisticResult


cv2.imwrite('/media/Decryption_Result.png', img)
  
# face = img[30:87, 70:129]
cv2.waitKey(0)

0 30 88 70 130


IndexError: ignored